name: fuckyou
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.8.0
  flutter_markdown: ^0.7.4+2
  firebase_messaging: ^15.1.5
  fl_chart: ^0.69.0 
  flutter_local_notifications: ^15.0.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  flutter_blue_plus: ^1.34.5
  multicast_dns: ^0.3.2+7
  url_launcher: ^6.3.1
  app_settings: ^5.1.1
  network_info_plus: ^6.1.1
  permission_handler: ^11.3.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/images/carebannerlogo.png
    - assets/test_image/



  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
